# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CyberPunkProject\CB2020_gm_toolkit\GUI_Pyqt\GUI_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(220, 210, 371, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Inventory = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Inventory.setObjectName("Inventory")
        self.gridLayout.addWidget(self.Inventory, 0, 1, 1, 1)
        self.Diceroller = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Diceroller.setObjectName("Diceroller")
        self.gridLayout.addWidget(self.Diceroller, 0, 0, 1, 1)
        self.DataFort = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.DataFort.setObjectName("DataFort")
        self.gridLayout.addWidget(self.DataFort, 1, 2, 1, 1)
        self.Fight = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Fight.setObjectName("Fight")
        self.gridLayout.addWidget(self.Fight, 1, 1, 1, 1)
        self.Shop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Shop.setObjectName("Shop")
        self.gridLayout.addWidget(self.Shop, 1, 0, 1, 1)
        self.Lab = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Lab.setObjectName("Lab")
        self.gridLayout.addWidget(self.Lab, 2, 0, 1, 1)
        self.Cybernetics = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.Cybernetics.setObjectName("Cybernetics")
        self.gridLayout.addWidget(self.Cybernetics, 2, 2, 1, 1)
        self.NPCGen = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.NPCGen.setObjectName("NPCGen")
        self.gridLayout.addWidget(self.NPCGen, 0, 2, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(270, 0, 262, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Inventory.setText(_translate("MainWindow", "Инвентарь"))
        self.Diceroller.setText(_translate("MainWindow", "Dice Roller"))
        self.DataFort.setText(_translate("MainWindow", "ДатаФорт"))
        self.Fight.setText(_translate("MainWindow", "Бой"))
        self.Shop.setText(_translate("MainWindow", "Магазин"))
        self.Lab.setText(_translate("MainWindow", "Лаборатория"))
        self.Cybernetics.setText(_translate("MainWindow", "Кибернетика"))
        self.NPCGen.setText(_translate("MainWindow", "Генератор NPC"))
        self.label.setText(_translate("MainWindow", "CyberPunk2020 GM Toolkit"))
