# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\CyberPunkProject\CB2020_gm_toolkit\GUI_Pyqt\Roller.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RollDice(object):
    def setupUi(self, RollDice):
        RollDice.setObjectName("RollDice")
        RollDice.resize(350, 270)
        self.centralwidget = QtWidgets.QWidget(RollDice)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 30, 262, 170))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Output = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Output.setReadOnly(True)
        self.Output.setObjectName("Output")
        self.gridLayout.addWidget(self.Output, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.BtnRoll = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.BtnRoll.setObjectName("BtnRoll")
        self.gridLayout.addWidget(self.BtnRoll, 3, 1, 1, 1)
        self.Input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.Input.setObjectName("Input")
        self.gridLayout.addWidget(self.Input, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        RollDice.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RollDice)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        RollDice.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RollDice)
        self.statusbar.setObjectName("statusbar")
        RollDice.setStatusBar(self.statusbar)

        self.retranslateUi(RollDice)
        QtCore.QMetaObject.connectSlotsByName(RollDice)

    def retranslateUi(self, RollDice):
        _translate = QtCore.QCoreApplication.translate
        RollDice.setWindowTitle(_translate("RollDice", "DiceRoller"))
        self.label.setText(_translate("RollDice", "Dice roller"))
        self.BtnRoll.setText(_translate("RollDice", "Бросить кубик"))
        self.label_2.setText(_translate("RollDice", "Пример ввода: 6d6 + 5"))
